@host=http://localhost:5135
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmODc0OGM3OS04NjU4LTRmZGEtOGIwNi02MTg0OTUzNTU4ZmMiLCJnaXZlbl9uYW1lIjoiTXVzdGFmYSIsImZhbWlseV9uYW1lIjoiTWFzdmkiLCJqdGkiOiI1YjkzZTgwNy0yZWJhLTQ5ZjItYWRkNS1iMTdkOWZkZWVjYTEiLCJleHAiOjE2Njk4MzE2NjQsImlzcyI6IkJ1YmJlckRpbm5lciIsImF1ZCI6IkJ1YmJlckRpbm5lciJ9.LHW_LlkYUpQj_Le0NFJWzouT0haauKzirD8kYoOiFQc
GET {{host}}/dinner
Authorization: Bearer {{token}}